[sncast.default]
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_10/pSdnR2sT6vam6LCSXurnEoTzoWvyCdwU"
accounts-file = "account.json"
account = "default"
wait-timeout = 300
wait-retry-interval = 5
